#!/bin/bash
set -e

echo "stopping agent service"
systemctl stop zabbix-agent.service
echo "removing /etc/zabbix"
rm -rf /etc/zabbix
echo "removing /usr/lib/zabbix"
rm -rf /usr/lib/zabbix
echo "removing /var/log/zabbix"
rm -rf /var/log/zabbix
echo "removing service file"
rm -f /usr/lib/systemd/system/zabbix-agent.service
echo "removing binaries"
rm /usr/sbin/zabbix_agentd
rm /usr/bin/zabbix_sender
rm /usr/bin/zabbix_get

echo "done"
